config/routes.rb
Deprecateme::Application.routes.draw do
  resources :votes
  resources :users
  
  match '/api/deprecated(.format)' => 'api#deprecated'
  match '/api/rubygem/:name(.format)' => 'api#rubygem'
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match 'login'             => 'sessions#new'
  match 'logout'            => 'sessions#destroy'
        '                      '
  match '/sessions/test'    => 'sessions#test'
        '                      '
  match 'search'            => 'gemcutter#search'
  match 'rubygem/:name'     => 'gemcutter#rubygem'
  match 'gemcutter/:action' => 'gemcutter'
        '                      '
  match 'profile'           => 'users#show'
  

  root :to => "gemcutter#search"

end

app/models/authorization.rb
class Authorization 
  include MongoMapper::Document
  
  key :provider, String, :required => true
  key :uid, String , :required => true
  key :user_id, ObjectId, :required => true
  
  belongs_to :user
  validates_uniqueness_of :uid, :scope => :provider
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user_id => user.id, :uid => hash['uid'], :provider => hash['provider'])
  end
end

app/models/user.rb
class User 
  include MongoMapper::Document

  key :name, String
  key :provider, String

  many :authorizations
  validates_uniqueness_of :name, :scope => :provider, :message => "must be unique"

  def self.create_from_hash!(hash)
    create(:name => hash['user_info']['name'] || hash['user_info'][:name], :provider => hash['provider'])
  end

  def total_votes
    self.votes.count
  end

  def votes
    Vote.by_user(self.id)
  end
end

app/models/vote.rb
require 'gemcutter'
class Vote
  include MongoMapper::Document

  key :name, String, :required => true 
  key :version, String, :required => true 
  key :user_id, ObjectId, :required => true 
  key :timestamp, Time, :required => true 

  belongs_to :user
  validates_uniqueness_of :user_id, :scope => :name, :message => "gets only one vote per gem!"

  scope :by_user,  proc {|user_id| where(:user_id => user_id) }
  scope :by_name,  proc {|name| where(:name => name) }
  scope :my_votes, proc {|user_id| where(:user_id => name) }

  def mine?(user_id)
    user_id == self.user_id
  end

  def self.deprecated?(name)
    Vote.by_name(name).count >= 5 #5 TODO: change back to 5 after testing is done!
  end

  def self.recent
    Vote.all(:order => 'timestamp DEC', :limit => 15)
  end
  
  def self.deprecated
    names =  Vote.all.map { |each| each.name }.uniq
    names.map  { |each|
      if deprecated?(each)
        info = Gemcutter.rubygem(each)
        { :name => info.name, :version => info.version, :uri => "/rubygem/#{info.name}", :total_votes => info.total_votes } 
      end 
    }.compact
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def rubygem
    name = params[:name]
    count = Vote.by_name(name).count
    deprecated = Vote.deprecated?(name)
    response = {:name => name, :vote_count => count, :deprecated => deprecated }
    respond_to do |format|
      format.html { render :json  => response }
      format.json { render :json  => response }
      format.xml  { render :xml   => response }
    end
  end
  
  def deprecated
    response = {:gems => Vote.deprecated }
    respond_to do |format|
      format.html { render :json  => response }
      format.json { render :json  => response }
      format.xml  { render :xml   => response }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
  
  def require_user
    unless current_user
      flash[:error] = "You must be logged in to access this page."
      redirect_to login_path
      return false
    end
  end
  
end

app/controllers/gemcutter_controller.rb
require 'gemcutter'

class GemcutterController < ApplicationController

  def search
    @gems = Gemcutter.search(params[:q]) unless params[:q].blank?
    @recent = Vote.recent
  end
  
  def rubygem
     @gem = Gemcutter.rubygem(params[:name]) unless params[:name].blank?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end 
  
  def create
    auth = request.env['rack.auth']
    unless @auth = Authorization.find_from_hash(auth)
      # Create a new user or add an auth to existing user, depending on
      # whether there is already a user signed in.
      @auth = Authorization.create_from_hash(auth, current_user)
    end
    # Log the authorizing user in.
    self.current_user = @auth.user
    unless current_user
      flash[:error] = "Could not log you in. Please try again laster. If the error persists, please contact support."
    end
    redirect_to root_url
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user
  
  def show
    @user = current_user
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :has_access?, :except => [:index, :show]
  
  # GET /votes
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  def show
    @vote = Vote.find(params[:id])
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  def create
    @vote = Vote.new(params[:vote])

    if @vote.save
      redirect_to(:back, :notice => 'Your vote has been registered <br /> Thank you for helping the community, you are a true Rubyist!')
    else
      @vote = Vote.by_user(params[:vote][:user_id]).by_name(params[:vote][:name]).last
      if @vote
        flash[:notice] = 'You have already voted for this gem <br /> Thank you for helping the community, you are a true Rubyist!'
        redirect_to :action => "show", :id => @vote.id
      else
        redirect_to(:back, :error => 'Could not register your vote at the moment, please try again later.')
      end
    end
  end

  # PUT /votes/1
  def update
    @vote = Vote.find(params[:id])

    if @vote.update_attributes(params[:vote])
      redirect_to(@vote, :notice => 'Vote was successfully updated.')
    else
      render :action => "edit" 
    end
  end

  # DELETE /votes/1
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    redirect_to(votes_url)
  end
  
private
  def has_access?
    unless signed_in?
      flash[:error] = 'You must sign in to vote!'
      redirect_to(:back)
    else
      !params[:id].blank? && current_user.id == Vote.find(params[:id]).user_id
    end
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gemcutter_helper.rb
module GemcutterHelper
  def display_info(search_result, attribute)
    "<strong>#{attribute.titleize}:</strong> #{search_result.send(attribute)}"
  end
  
  def display_dependencies(search_result, attribute)
    "<strong>#{attribute.titleize}:</strong> <br/> " + search_result.send(attribute).inject("") { |display, dependency| 
      display += link_to("#{dependency[:name]} #{dependency[:requirements]}", :controller => 'gemcutter', :action => 'rubygem', :name => dependency[:name])
      display += image_tag("/images/deprecated-stamp-straight.png", :border => 0, :width => 150, :height => 25) if Vote.deprecated?(dependency[:name])
      display += "<br />"
    }
  end
  
  def display_url(search_result, attribute)
    "<strong>#{attribute.titleize}:</strong> " + link_to(search_result.send(attribute), search_result.send(attribute))
  end
  
  def vote_count name
    "<red>(-#{Vote.by_name(name).count})</red>" unless Vote.by_name(name).count.blank? || Vote.by_name(name).count == 0
  end
  
  def display_dependency dependency
    link_to "#{dependency.name}, #{dependency.version}", :controller => 'gemcutter', :action => 'rubygem', :name => dependency.name 
  end
  
  def display_last_commit_date date
    unless date.blank?
       Time.parse(date).strftime("%m/%d/%Y %H:%M:%S") + " (" + time_ago_in_words(Time.parse(date)) + " ago)"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/gemcutter/rubygem.html.erb
<% unless @gem.blank? %>
<div id="gem">
	<h2><%= @gem.name %> <%= raw vote_count(@gem.name) %></h2>

	<div class="gem-info">
		<h3>Info</h3>
		<p>
			<%= raw display_info(@gem, 'name') %>
		</p>
		<p>
			<%= raw display_info(@gem, 'info') %>
		</p>
		<p>
			<%= raw display_info(@gem, 'version') %>
		</p>
		<p>
			<%= raw display_info(@gem, 'version_downloads') %>
		</p>
		<p>
			<%= raw display_info(@gem, 'authors') %>
		</p>
		<p>
			<%= raw display_info(@gem, 'downloads') %>
		</p>
		<p>
			<%= raw display_url(@gem, 'project_uri') %>
		</p>
		<p>
			<%= raw display_url(@gem, 'gem_uri') %>
		</p>
		<p>
			<%= raw display_url(@gem, 'homepage_uri') %>
		</p>
		<p>
			<%= raw display_url(@gem, 'wiki_uri') %>
		</p>
		<p>
			<%= raw display_url(@gem, 'documentation_uri') %>
		</p>
		<p>
			<%= raw display_url(@gem, 'mailing_list_uri') %>
		</p>
		<p>
			<%= raw display_url(@gem, 'source_code_uri') %>
		</p>
		<p>
			<%= raw display_url(@gem, 'bug_tracker_uri') %>
		</p>
		<p>
			<%= raw display_dependencies(@gem, 'runtime_dependencies') %>
		</p>
		<p>
			<%= raw display_dependencies(@gem, 'development_dependencies') %>
		</p>
	</div>
	<div class='deprecated-big'>
		<%= image_tag("/images/deprecated-stamp-right.png", :border => 0) if Vote.deprecated?(@gem.name) %>
	</div>
	
	<div class='activity-info'>

		<div class="project-status">
			<h3>Project Status</h3>
			<p>
				<strong>Total Votes for Deprecation:</strong> <%= Vote.by_name(@gem.name).count %><br />
			</p>
			<p>
				<strong>Current Version Downloads:</strong> <%= @gem.version_downloads %><br />
			</p>
			<p>
				<strong>Total Downloads:</strong> <%= @gem.downloads %><br />
			</p>
			<p>
				<strong>Last Commit Date:</strong> <%= display_last_commit_date @gem.last_commit_date %><br />
			</p>
		</div>
		<div class="dependents">
			<h3>Possible Dependents</h3>
			<% @gem.dependents.each do |dependent| %>
				<%= display_dependency dependent %> <%= image_tag("/images/deprecated-stamp-straight.png", :border => 0, :width => 150, :height => 25) if Vote.deprecated?(dependent.name) %>
				<div class="clear"> </div>
				<br />
			<% end %>
		</div>
		
	</div>
	
	<% if signed_in? %>
		<div class='deprecate-me'>
			<%= link_to image_tag("/images/deprecateme-stamp.png", :border => 0, :width => 400), votes_path(:vote => { :name => @gem.name, :version => @gem.version, :user_id => current_user.id, :timestamp => Time.now }), :method => :post %>
		</div>
	<% end %>
	
	<div class="clear"> </div>
	<hr />
	
	
	
	<div class="clear"> </div>
</div>

<% else %>
	<h2><red>Gem Not Found!</red></h2>
<% end %>
   

app/views/gemcutter/search.html.erb
<%= form_tag(search_path, :method => "get") do %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<% unless @gems.blank? %>
	<% @gems.each do |each| %>
		<div class="gem">
			<div class="gem-info-list">
				<h2><%= each.name %>  <%= raw vote_count(each.name) %></h2>
				<p>
					<%= raw display_info(each, 'name') %>
				</p>
				<p>
					<%= raw display_info(each, 'info') %>
				</p>
				<p>
					<%= raw display_info(each, 'version') %>
				</p>
				<p>
					<%= link_to "more info", :controller => :gemcutter, :action => :rubygem, :name => each.name %>
				</p>
			</div>
			<div class='deprecated'>
				<%= image_tag("/images/deprecated-stamp.png", :border => 0, :width => 200, :height => 200) if Vote.deprecated?(each.name) %>
			</div>
			<div class="clear"> </div>
			<hr />
		</div>
	<% end %>
	
<% else %>

	<hr />
	<h2>Recent Activity</h2>

	<% @recent.each do |activity| %>
		<div class="gem">
			<red><%= link_to activity.name, :controller => :gemcutter, :action => :rubygem, :name => activity.name %></red> voted down by <strong><%= activity.user.name %></strong> at <%= activity.timestamp.strftime("%m/%d/%Y %H:%M:%S") %>
		</div>
	<% end unless @recent.blank? %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeprecateMe</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="container">
	<div id="header">
		<div id="title">
			<h1><%= link_to "DeprecateMe", root_url %></h1>
		</div>
		<div id="left-header">
			<div id='user-status'>
				<% if signed_in? %>
					Hello <%= link_to current_user.name, profile_path %>. <%= link_to "Logout!", logout_path %> 
				<% else %>
					To vote on a gem, you must <%= link_to "sign in!", login_path %>
				<% end %>
			</div>
			<div id="search">
				<%= form_tag(search_path, :method => "get") do %>
				  <%= text_field_tag(:q) %>
				  <%= submit_tag("Search") %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="clear"> </div>
	<div id="nav">
		<%= link_to "Home", root_path %> | 
		<%= link_to "About", page_path("about") %> | 
		<%= link_to "API", page_path("api_docs") %> |
	</div>
	<div id='wrapper'>
		<%- flash.each do |name, msg| -%>
			<%= content_tag :div, raw(msg), :id => "flash_#{name}" %>
		<%- end -%>
		<%= yield %>
	</div>
	<div class="clear"> </div>
	<div id="footer">
		<div id="credits">
			<h3>Credits</h3>
			<p>Theme: Completely and Shamelessly Stolen from <a href="http://rubygems.org">RubyGems.org</a><p>
			<p>Social Buttons: <a href="http://www.komodomedia.com/download/#sign-in-with-twitter-facebook-and-openid">Komodo Media</a></p>
			<p>Idea: Discussion at <a href="http://rubydcamp.org">RubyDCamp</a> about staying up to date with the state of ruby gems</p>
		</div>
		<div id="team">
			<h3>Team</h3>
			<p>Team: <a href="http://rumbl.in/g/o19s">o19s</a></p>
			<p>Developers: <a href="http://twitter.com/ychaer">@ychaker</a> (<a href="http://http://github.com/ychaker">github</a>) [+ everyone else who bailed out on me at the last minute!]</p>
		</div>
		<div class="clear"> </div>
		<p style="text-align:center;">
			RailsRumble 2010 entry for team <a href="http://rumbl.in/g/o19s">o19s</a>. Vote for us! Thanks :)
		</p>
	</div>
	<div class="clear"> </div>
</div>

</body>
<script type="text/javascript">
  var rumbleUrl = 'http://rumbl.in/g/o19s';
</script>
<script type="text/javascript" src="http://blog.railsrumble.com/javascripts/rumble-r10-sash.js"></script>
</html>

app/views/pages/about.html.erb
<h2>What is Deprecate Me?</h2>
<p>
	Have you ever tried to find a gem for your needs, only to realize half way through the implementation that the gem is outdated?
</p>

<p>
	Have you ever used a gem, only to find out later that it is no longer supported?
</p>

<p>
	Have you ever dropped in on a conversation where a bunch of fellow rubyists are talking about how awful a gem is (you know, the one you've just used for your app that just went to production)?
</p>

<p>
	<strong>Don't you wish you had a community site you rely on for this kind of information?</strong>
</p>

<p>
	Well now you can come to <%= link_to "Deprecate Me", root_path %> to check on a particular gem's status.
</p>

<h2>Genesis</h2>
<p>
	At <a href="http://rubydcamp.org">RubyDCamp</a>, a session was held on the topic of the state of the ruby ecosystem. One the subjects that was discussed is the speed at which the ecosystem is evolving. Today's gem is tomorrow's ash. Even with all the means of communication we have, including twitter, staying up to date on which is the latest and greatest tool for the job is difficult.
</p>

<p>
	<strong>So what is the solution?</strong> The answer is not easy and simple. How do you gage if a certain gem is deprecated? Or know if the maintainer is no longer supporting it? What if the person behind it just dropped off the face of the earth (yes I'm talking to you _why!)?
</p>

<p>
	Well, you've got a community behind you. The Ruby community is the best I've worked with. So lets lean on the community for that sort of thing.
</p>

<h2>How?</h2>
<p>
	If you are a gem author and are no longer maintain a project, mark it as deprecated.
</p>

<p>
	If you know for a FACT that a gem is deprecated, mark it as deprecated.
</p>

<p>
	If a gem is broken or outdated and you know of a better alternative, mark it as deprecated.
</p>

<p>
	If a gem source code has not been updated in a while, and issues and tickets not closed or addressed in a while, mark it as deprecated.
</p>

<h3>Instructions</h3>
<p>
	To vote for a gem to be deprecated, you must <%= link_to "sign in", login_path %>. We only allow one vote per user. You can sign in using any of the following: Twitter, Facebook, or LinkedIn.
</p>

<p>
	Search for the gem you are looking using the search box in the header or on the home page:<br />
	<%= image_tag "/images/screenshots/search.png", :border => 2, :width => 600, :height => 400 %>
</p>
	
<p>
	Navigate to the gem's page by clicking on the 'more info' link:<br />
	<%= image_tag "/images/screenshots/gempage.png", :border => 2, :width => 600, :height => 400 %>
</p>

<p>
	Once at the gem's page, you can look the gem's status. The list of dependents, last commit date and number of downloads can help you determine whether a gem is still active or not:<br />
	<%= image_tag "/images/screenshots/project-status.png", :border => 2, :width => 400, :height => 400 %>
</p>

<p>
	You can vote a gem to be deprecated by hitting the 'Deprecate Me!' stamp. <strong>A gem with 5 votes or more will be marked as 'Deprecated'</strong> (5 is a low enough number to work for the RailsRumble, may change in the future):<br />
	<%= image_tag "/images/screenshots/deprecated.png", :border => 2, :width => 600, :height => 400 %>
</p>

<p>
	A deprecated gem will be marked as so in search results:<br />
	<%= image_tag "/images/screenshots/deprecated-list.png", :border => 2, :width => 600, :height => 400 %>
</p>

	
<h2>Rules of Engagement</h2>

<p>
	<strong>Deprecate Me is NOT a popularity contest</strong>
</p>

<p>
	Do NOT mark a gem as deprecated just because you want people to adopt yours instead
</p>

<p>
	One vote per user.
</p>

<h2>Why Did You Steal RubyGems.org's Theme?</h2>
<p>
	The belief is that the functionality provided here can and should be added to RubyGems.org (and/or github). Deprecate Me should be used in conjunction with RubGems.org. In fact, the search functionality and acquiring the gem information use their <a href="http://rubygems.org/pages/api_docs">API</a>. So the theme reinforces the collaboration between Deprecate Me and RubyGems.org
</p>

app/views/pages/api_docs.html.erb
<div id='api-docs'>

<h2><a href="/pages/api_docs">API Docs</a></h2> 
 
<h4>API Methods</h4> 
<ul id="docs"> 
  <li><a href="#rubygem">RubyGem Method</a>: Check the status of a gem</li> 
  <li><a href="#deprecated">Deprecated Method</a>: Get list of all deprecated gems</li>
</ul> 
 
<h4 id="rubygem">RubyGem Method</h4> 
 
<h5 class="api">GET - /api/rubygem/[name].(json|xml)</h5> 
<p> 
  Returns name, vote count and deprecated status for the given gem. For example, here's restful_authentication:
  <pre>
		<code>
$ curl http://o19s.r10.railsrumble.com/api/rubygem/restful_authentication.json
 
{
  name: "restful_authentication",
  vote_count: 6,
  deprecated: true
}
 
$ curl http://o19s.r10.railsrumble.com/api/rubygem/restful_authentication.xml

&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;hash&gt;
  &lt;name&gt;restful_authentication&lt;/name&gt;
  &lt;vote-count type="integer"&gt;6&lt;/vote-count&gt;
  &lt;deprecated  type="boolean"&gt;true&lt;/deprecated&gt;
&lt;/hash&gt;

		</code>
	</pre> 
</p> 

<h4 id="deprecated">Deprecated Method</h4> 
<h5 class="api">GET - /api/deprecated.(json|xml)</h5> 
<p> 
  List all gems that have been marked as deprecated. Returns an array of the XML or JSON representation with the name, version, uri and total number of votes.

	<pre><code>$ curl http://o19s.r10.railsrumble.com/api/deprecated.json

{
  -gems: [
  -{
    name: "restful_authentication",
    version: "1.1.6",
    uri: "/rubygem/restful_authentication",
    total_votes: 6
  }
  ]
}
 
$ curl http://o19s.r10.railsrumble.com/api/deprecated.xml


&lt;hash&gt;
  &lt;gems type="array"&gt;
    &lt;gem&gt;
      &lt;name&gt;restful_authentication&lt;/name&gt;
      &lt;version&gt;1.1.6&lt;/version&gt;
      &lt;uri&gt;/rubygem/restful_authentication&lt;/uri&gt;
      &lt;total-votes type="integer"&gt;6&lt;/total-votes&gt;
    &lt;/gem>
  &lt;/gems>
&lt;/hash>

</code></pre>
</p> 
</div>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>

<div id='stats'>
	<p>Number of Votes: <%= @user.total_votes %></p>
	
	<div id='activity'>
		<h3>Activity</h3>
		<% @user.votes.each do |vote| %>
		<div class='user-vote'>
			<p>Voted for <%= link_to vote.name, :controller => :gemcutter, :action => :rubygem, :name => vote.name %> (version: <%= vote.version %>), on <%= vote.timestamp.strftime("%m/%d/%Y %H:%M:%S") %> | <%= link_to 'Show', vote %></p>
		</div>
		<% end %>
	</div>
</div>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :timestamp, :value => Time.now %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %>
| <%= link_to 'Back', :back %>

<% if @vote.mine?(current_user.id) %>
 |  <%= link_to 'Destroy', @vote, :confirm => 'Are you sure?', :method => :delete %>
<% end if signed_in? %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Version</th>
    <th>User</th>
    <th>Timestanp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.name %></td>
    <td><%= vote.version %></td>
    <td><%= vote.user.name %></td>
    <td><%= vote.timestamp.strftime("%m/%d/%Y %H:%M:%S") %></td>
    <td><%= link_to 'Show', vote %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/votes/show.html.erb
<p>
  <b>Name:</b>
  <%= @vote.name %>
</p>

<p>
  <b>Version:</b>
  <%= @vote.version %>
</p>

<p>
  <b>User:</b>
  <%= @vote.user.name %>
</p>

<p>
  <b>Timestanp:</b>
  <%= @vote.timestamp %>
</p>



<%= link_to 'Back', :back %>


<% if @vote.mine?(current_user.id) %>
 |  <%= link_to 'Edit', edit_vote_path(@vote) %>
 |  <%= link_to 'Destroy', @vote, :confirm => 'Are you sure?', :method => :delete %>
<% end if signed_in? %>